In [1]:
import numpy as np
import pandas as pd

In [13]:
import pandas as pd
df = pd.read_csv(r"C:\Proyectos\Salle\SeminarioDataScience\archivos_base_python_data_science_big_data_esencial\base_datos_2008.csv\base_datos_2008.csv", nrows=1000)

In [14]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0

In [15]:
df.tail()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
995,2008,1,3,4,2154.0,2040,2314.0,2205,WN,428,...,4.0,13.0,0,NaN,0,2.0,0.0,0.0,0.0,67.0
996,2008,1,3,4,1322.0,1245,1444.0,1410,WN,500,...,3.0,15.0,0,NaN,0,34.0,0.0,0.0,0.0,0.0
997,2008,1,3,4,701.0,700,823.0,825,WN,565,...,4.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
998,2008,1,3,4,1012.0,1010,1136.0,1135,WN,752,...,5.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
999,2008,1,3,4,834.0,830,955.0,955,WN,762,...,4.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [16]:
df.isnull().sum()

Year                   0
Month                  0
DayofMonth             0
DayOfWeek              0
DepTime               12
CRSDepTime             0
ArrTime               12
CRSArrTime             0
UniqueCarrier          0
FlightNum              0
TailNum               12
ActualElapsedTime     12
CRSElapsedTime         0
AirTime               12
ArrDelay              12
DepDelay              12
Origin                 0
Dest                   0
Distance               0
TaxiIn                12
TaxiOut               12
Cancelled              0
CancellationCode     988
Diverted               0
CarrierDelay         490
WeatherDelay         490
NASDelay             490
SecurityDelay        490
LateAircraftDelay    490
dtype: int64

In [17]:
dfok = df["ArrDelay"].dropna()
dfok.head()

0   -14.0
1     2.0
2    14.0
3    -6.0
4    34.0
Name: ArrDelay, dtype: float64

In [18]:
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2008,1,3,4,2154.0,2040,2314.0,2205,WN,428,...,4.0,13.0,0,NaN,0,2.0,0.0,0.0,0.0,67.0
996,2008,1,3,4,1322.0,1245,1444.0,1410,WN,500,...,3.0,15.0,0,NaN,0,34.0,0.0,0.0,0.0,0.0
997,2008,1,3,4,701.0,700,823.0,825,WN,565,...,4.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
998,2008,1,3,4,1012.0,1010,1136.0,1135,WN,752,...,5.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
999,2008,1,3,4,834.0,830,955.0,955,WN,762,...,4.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [19]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0

In [20]:
df.tail()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
995,2008,1,3,4,2154.0,2040,2314.0,2205,WN,428,...,4.0,13.0,0,NaN,0,2.0,0.0,0.0,0.0,67.0
996,2008,1,3,4,1322.0,1245,1444.0,1410,WN,500,...,3.0,15.0,0,NaN,0,34.0,0.0,0.0,0.0,0.0
997,2008,1,3,4,701.0,700,823.0,825,WN,565,...,4.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
998,2008,1,3,4,1012.0,1010,1136.0,1135,WN,752,...,5.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
999,2008,1,3,4,834.0,830,955.0,955,WN,762,...,4.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [21]:
df.head(10)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,...,4.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,509,...,3.0,7.0,0,NaN,0,10.0,0.0,0.0,0.0,47.0
7,2008,1,3,4,1039.0,1040,1132.0,1150,WN,535,...,7.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
8,2008,1,3,4,617.0,615,652.0,650,WN,11,...,6.0,19.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
9,2008,1,3,4,1620.0,1620,1639.0,1655,WN,810,...,3.0,6.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [22]:
df.sample(frac = 1)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
320,2008,1,3,4,1735.0,1710,2010.0,1955,WN,230,...,4.0,10.0,0,NaN,0,0.0,0.0,4.0,0.0,11.0
835,2008,1,3,4,1542.0,1515,1805.0,1730,WN,2445,...,8.0,11.0,0,NaN,0,27.0,0.0,8.0,0.0,0.0
435,2008,1,3,4,1725.0,1655,2238.0,2225,WN,71,...,4.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
597,2008,1,3,4,622.0,615,750.0,755,WN,10,...,3.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
692,2008,1,3,4,2334.0,1950,157.0,2235,WN,106,...,4.0,6.0,0,NaN,0,15.0,0.0,0.0,0.0,187.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,2008,1,3,4,1824.0,1715,117.0,25,WN,2383,...,2.0,10.0,0,NaN,0,48.0,0.0,0.0,0.0,4.0
674,2008,1,3,4,2033.0,1905,2249.0,2150,WN,3568,...,4.0,7.0,0,NaN,0,59.0,0.0,0.0,0.0,0.0
329,2008,1,3,4,1925.0,1735,2201.0,2025,WN,1671,...,3.0,8.0,0,NaN,0,5.0,0.0,0.0,0.0,91.0
509,2008,1,3,4,645.0,635,822.0,820,WN,1844,...,10.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
891,2008,1,3,4,634.0,620,952.0,950,WN,979,...,4.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [23]:
df.sample(frac = 1,random_state=1)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
507,2008,1,3,4,2016.0,2020,2141.0,2130,WN,3774,...,20.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
818,2008,1,3,4,633.0,630,934.0,925,WN,235,...,6.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
452,2008,1,3,4,2007.0,2010,2102.0,2110,WN,2542,...,3.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
368,2008,1,3,4,1827.0,1800,1945.0,1915,WN,829,...,4.0,11.0,0,NaN,0,0.0,0.0,3.0,0.0,27.0
242,2008,1,3,4,2137.0,2040,2251.0,2155,WN,2273,...,4.0,14.0,0,NaN,0,0.0,0.0,0.0,0.0,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
767,2008,1,3,4,1508.0,1430,1700.0,1630,WN,3844,...,4.0,8.0,0,NaN,0,27.0,0.0,0.0,0.0,3.0
72,2008,1,3,4,1820.0,1825,1946.0,1955,WN,549,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
908,2008,1,3,4,1206.0,1135,1511.0,1500,WN,976,...,21.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
235,2008,1,3,4,1716.0,1630,1830.0,1755,WN,239,...,4.0,10.0,0,NaN,0,11.0,0.0,0.0,0.0,24.0
37,2008,1,3,4,1812.0,1650,1927.0,1815,WN,422,...,6.0,11.0,0,NaN,0,3.0,0.0,0.0,0.0,69.0

In [24]:
df = df.sample(frac = 1)

In [25]:
df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [26]:
df.Origin

14     IND
425    LAX
325    LAX
838    MDW
417    LAX
      ...
624    MCO
132    LAS
809    MDW
753    MDW
932    MSY
Name: Origin, Length: 1000, dtype: object

In [40]:
df.dtypes

Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier         object
FlightNum              int64
TailNum               object
ActualElapsedTime    float64
CRSElapsedTime         int64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin                object
Dest                  object
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode      object
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [44]:
df.values

array([[2008, 1, 3, ..., nan, nan, nan],
       [2008, 1, 3, ..., nan, nan, nan],
       [2008, 1, 3, ..., nan, nan, nan],
       ...,
       [2008, 1, 3, ..., 0.0, 0.0, 0.0],
       [2008, 1, 3, ..., 0.0, 0.0, 27.0],
       [2008, 1, 3, ..., 0.0, 0.0, 30.0]], dtype=object)

In [45]:
df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [46]:
df["FlightNum"].head()

984    3772
998     752
358    1930
834    1414
181     237
Name: FlightNum, dtype: int64

In [47]:
df[0:10]

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
984,2008,1,3,4,817.0,805,919.0,910,WN,3772,...,2.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
998,2008,1,3,4,1012.0,1010,1136.0,1135,WN,752,...,5.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
358,2008,1,3,4,630.0,625,1209.0,1220,WN,1930,...,4.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
834,2008,1,3,4,750.0,730,1002.0,950,WN,1414,...,6.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
181,2008,1,3,4,1251.0,1205,1425.0,1345,WN,237,...,3.0,15.0,0,NaN,0,2.0,0.0,0.0,0.0,38.0
421,2008,1,3,4,1114.0,1045,1347.0,1330,WN,963,...,3.0,10.0,0,NaN,0,4.0,0.0,0.0,0.0,13.0
762,2008,1,3,4,650.0,615,840.0,815,WN,891,...,3.0,11.0,0,NaN,0,0.0,25.0,0.0,0.0,0.0
129,2008,1,3,4,1725.0,1620,1940.0,1850,WN,2803,...,4.0,15.0,0,NaN,0,50.0,0.0,0.0,0.0,0.0
431,2008,1,3,4,1524.0,1505,1634.0,1620,WN,2720,...,4.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
773,2008,1,3,4,1414.0,1400,1641.0,1630,WN,3149,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [48]:
df["ArrDelay"]

984     9.0
998     1.0
358   -11.0
834    12.0
181    40.0
       ...
248    20.0
445     0.0
869    39.0
443    31.0
91     49.0
Name: ArrDelay, Length: 1000, dtype: float64

In [50]:
df[df["ArrDelay"] < 60].head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
984,2008,1,3,4,817.0,805,919.0,910,WN,3772,...,2.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
998,2008,1,3,4,1012.0,1010,1136.0,1135,WN,752,...,5.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
358,2008,1,3,4,630.0,625,1209.0,1220,WN,1930,...,4.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
834,2008,1,3,4,750.0,730,1002.0,950,WN,1414,...,6.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
181,2008,1,3,4,1251.0,1205,1425.0,1345,WN,237,...,3.0,15.0,0,NaN,0,2.0,0.0,0.0,0.0,38.0

In [51]:
df[df["ArrDelay"] !=  60].head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
984,2008,1,3,4,817.0,805,919.0,910,WN,3772,...,2.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
998,2008,1,3,4,1012.0,1010,1136.0,1135,WN,752,...,5.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
358,2008,1,3,4,630.0,625,1209.0,1220,WN,1930,...,4.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
834,2008,1,3,4,750.0,730,1002.0,950,WN,1414,...,6.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
181,2008,1,3,4,1251.0,1205,1425.0,1345,WN,237,...,3.0,15.0,0,NaN,0,2.0,0.0,0.0,0.0,38.0

In [52]:
df[df["Origin"] == "LAX"].head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
358,2008,1,3,4,630.0,625,1209.0,1220,WN,1930,...,4.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
421,2008,1,3,4,1114.0,1045,1347.0,1330,WN,963,...,3.0,10.0,0,NaN,0,4.0,0.0,0.0,0.0,13.0
431,2008,1,3,4,1524.0,1505,1634.0,1620,WN,2720,...,4.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
427,2008,1,3,4,2013.0,1910,2121.0,2025,WN,1015,...,3.0,7.0,0,NaN,0,0.0,0.0,0.0,0.0,56.0
344,2008,1,3,4,744.0,740,838.0,840,WN,2111,...,3.0,5.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [54]:
df [   (  df["ArrDelay"] == 60 ) | ( df ["Origin"] == "LAX"  )    ].head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
358,2008,1,3,4,630.0,625,1209.0,1220,WN,1930,...,4.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
421,2008,1,3,4,1114.0,1045,1347.0,1330,WN,963,...,3.0,10.0,0,NaN,0,4.0,0.0,0.0,0.0,13.0
431,2008,1,3,4,1524.0,1505,1634.0,1620,WN,2720,...,4.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
427,2008,1,3,4,2013.0,1910,2121.0,2025,WN,1015,...,3.0,7.0,0,NaN,0,0.0,0.0,0.0,0.0,56.0
344,2008,1,3,4,744.0,740,838.0,840,WN,2111,...,3.0,5.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [71]:
df[df.Origin.isin(["LAX","HOU"])].head()  # in

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
358,2008,1,3,4,630.0,625,1209.0,1220,WN,1930,...,4.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
421,2008,1,3,4,1114.0,1045,1347.0,1330,WN,963,...,3.0,10.0,0,NaN,0,4.0,0.0,0.0,0.0,13.0
431,2008,1,3,4,1524.0,1505,1634.0,1620,WN,2720,...,4.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
427,2008,1,3,4,2013.0,1910,2121.0,2025,WN,1015,...,3.0,7.0,0,NaN,0,0.0,0.0,0.0,0.0,56.0
344,2008,1,3,4,744.0,740,838.0,840,WN,2111,...,3.0,5.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [73]:
df[pd.isna(df["ArrDelay"])].head(20)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
676,2008,1,3,4,NaN,845,NaN,1140,WN,437,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
884,2008,1,3,4,NaN,1445,NaN,1550,WN,2205,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
727,2008,1,3,4,NaN,600,NaN,805,WN,3326,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
399,2008,1,3,4,NaN,905,NaN,1025,WN,469,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
178,2008,1,3,4,NaN,700,NaN,830,WN,126,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
881,2008,1,3,4,NaN,1110,NaN,1215,WN,1402,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
977,2008,1,3,4,NaN,1310,NaN,1415,WN,2283,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
415,2008,1,3,4,NaN,1930,NaN,2035,WN,2528,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
686,2008,1,3,4,NaN,1925,NaN,2045,WN,934,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
401,2008,1,3,4,NaN,1620,NaN,1740,WN,618,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
974,2008,1,3,4,NaN,1705,NaN,1810,WN,1219,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
373,2008,1,3,4,NaN,1100,NaN,1215,WN,1146,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN

In [74]:
len(df[pd.isna(df["ArrDelay"])])

12

In [76]:
len(df.columns)

29

In [77]:
df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [78]:
df["Horas"] = round(df["ArrDelay"] / 60)

In [79]:
df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay',
       'Horas'],
      dtype='object')

In [80]:
len(df.columns)

30

In [81]:
df["Horas"].head()

984    0.0
998    0.0
358   -0.0
834    0.0
181    1.0
Name: Horas, dtype: float64

In [82]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Horas
984,2008,1,3,4,817.0,805,919.0,910,WN,3772,...,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0
998,2008,1,3,4,1012.0,1010,1136.0,1135,WN,752,...,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0
358,2008,1,3,4,630.0,625,1209.0,1220,WN,1930,...,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,-0.0
834,2008,1,3,4,750.0,730,1002.0,950,WN,1414,...,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0
181,2008,1,3,4,1251.0,1205,1425.0,1345,WN,237,...,15.0,0,NaN,0,2.0,0.0,0.0,0.0,38.0,1.0

In [84]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Horas
984,2008,1,3,4,817.0,805,919.0,910,WN,3772,...,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0
998,2008,1,3,4,1012.0,1010,1136.0,1135,WN,752,...,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0
358,2008,1,3,4,630.0,625,1209.0,1220,WN,1930,...,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,-0.0
834,2008,1,3,4,750.0,730,1002.0,950,WN,1414,...,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0
181,2008,1,3,4,1251.0,1205,1425.0,1345,WN,237,...,15.0,0,NaN,0,2.0,0.0,0.0,0.0,38.0,1.0

In [83]:
df.drop(["Diverted","Cancelled","Year"], axis=1)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Horas
984,1,3,4,817.0,805,919.0,910,WN,3772,N708SA,...,325,2.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
998,1,3,4,1012.0,1010,1136.0,1135,WN,752,N680AA,...,407,5.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
358,1,3,4,630.0,625,1209.0,1220,WN,1930,N724SW,...,1750,4.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.0
834,1,3,4,750.0,730,1002.0,950,WN,1414,N402WN,...,402,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
181,1,3,4,1251.0,1205,1425.0,1345,WN,237,N281WN,...,407,3.0,15.0,NaN,2.0,0.0,0.0,0.0,38.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,1,3,4,1348.0,1330,1455.0,1435,WN,341,N315SW,...,258,2.0,14.0,NaN,8.0,0.0,2.0,0.0,10.0,0.0
445,1,3,4,840.0,840,940.0,940,WN,15,N341SW,...,293,3.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
869,1,3,4,824.0,735,1059.0,1020,WN,220,N275WN,...,1838,4.0,11.0,NaN,39.0,0.0,0.0,0.0,0.0,1.0
443,1,3,4,1825.0,1745,1921.0,1850,WN,555,N506SW,...,341,4.0,5.0,NaN,4.0,0.0,0.0,0.0,27.0,1.0
91,1,3,4,1739.0,1640,114.0,25,WN,1018,N245WN,...,2298,9.0,13.0,NaN,19.0,0.0,0.0,0.0,30.0,1.0

In [85]:
df.drop(["Diverted","Cancelled","Year"], axis=1, inplace=True)

In [86]:
df.head()

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Horas
984,1,3,4,817.0,805,919.0,910,WN,3772,N708SA,...,325,2.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
998,1,3,4,1012.0,1010,1136.0,1135,WN,752,N680AA,...,407,5.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
358,1,3,4,630.0,625,1209.0,1220,WN,1930,N724SW,...,1750,4.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.0
834,1,3,4,750.0,730,1002.0,950,WN,1414,N402WN,...,402,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
181,1,3,4,1251.0,1205,1425.0,1345,WN,237,N281WN,...,407,3.0,15.0,NaN,2.0,0.0,0.0,0.0,38.0,1.0

In [88]:
len(df)

1000

In [89]:
df.drop(515)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Horas
984,1,3,4,817.0,805,919.0,910,WN,3772,N708SA,...,325,2.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
998,1,3,4,1012.0,1010,1136.0,1135,WN,752,N680AA,...,407,5.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
358,1,3,4,630.0,625,1209.0,1220,WN,1930,N724SW,...,1750,4.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.0
834,1,3,4,750.0,730,1002.0,950,WN,1414,N402WN,...,402,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
181,1,3,4,1251.0,1205,1425.0,1345,WN,237,N281WN,...,407,3.0,15.0,NaN,2.0,0.0,0.0,0.0,38.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,1,3,4,1348.0,1330,1455.0,1435,WN,341,N315SW,...,258,2.0,14.0,NaN,8.0,0.0,2.0,0.0,10.0,0.0
445,1,3,4,840.0,840,940.0,940,WN,15,N341SW,...,293,3.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
869,1,3,4,824.0,735,1059.0,1020,WN,220,N275WN,...,1838,4.0,11.0,NaN,39.0,0.0,0.0,0.0,0.0,1.0
443,1,3,4,1825.0,1745,1921.0,1850,WN,555,N506SW,...,341,4.0,5.0,NaN,4.0,0.0,0.0,0.0,27.0,1.0
91,1,3,4,1739.0,1640,114.0,25,WN,1018,N245WN,...,2298,9.0,13.0,NaN,19.0,0.0,0.0,0.0,30.0,1.0

In [ ]:
dfLAX = df[df.Origin == "LAX"]
dfOAK = df[df.Origin == "OAK"]

In [91]:
dfLAX = df[df.Origin == "LAX"]

In [93]:
dfOAK = df[df.Origin == "OAK"]

In [95]:
print(len(dfOAK), " ", len(dfLAX))

38   122

In [90]:
df.drop(range(0,100))

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Horas
984,1,3,4,817.0,805,919.0,910,WN,3772,N708SA,...,325,2.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
998,1,3,4,1012.0,1010,1136.0,1135,WN,752,N680AA,...,407,5.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
358,1,3,4,630.0,625,1209.0,1220,WN,1930,N724SW,...,1750,4.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.0
834,1,3,4,750.0,730,1002.0,950,WN,1414,N402WN,...,402,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
181,1,3,4,1251.0,1205,1425.0,1345,WN,237,N281WN,...,407,3.0,15.0,NaN,2.0,0.0,0.0,0.0,38.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,1,3,4,946.0,940,1045.0,1045,WN,1037,N734SA,...,258,2.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
248,1,3,4,1348.0,1330,1455.0,1435,WN,341,N315SW,...,258,2.0,14.0,NaN,8.0,0.0,2.0,0.0,10.0,0.0
445,1,3,4,840.0,840,940.0,940,WN,15,N341SW,...,293,3.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
869,1,3,4,824.0,735,1059.0,1020,WN,220,N275WN,...,1838,4.0,11.0,NaN,39.0,0.0,0.0,0.0,0.0,1.0
443,1,3,4,1825.0,1745,1921.0,1850,WN,555,N506SW,...,341,4.0,5.0,NaN,4.0,0.0,0.0,0.0,27.0,1.0

In [96]:
dfLAX.append(dfOAK)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Horas
358,1,3,4,630.0,625,1209.0,1220,WN,1930,N724SW,...,1750,4.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.0
421,1,3,4,1114.0,1045,1347.0,1330,WN,963,N311SW,...,590,3.0,10.0,NaN,4.0,0.0,0.0,0.0,13.0,0.0
431,1,3,4,1524.0,1505,1634.0,1620,WN,2720,N629SW,...,373,4.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
427,1,3,4,2013.0,1910,2121.0,2025,WN,1015,N384SW,...,373,3.0,7.0,NaN,0.0,0.0,0.0,0.0,56.0,1.0
344,1,3,4,744.0,740,838.0,840,WN,2111,N673AA,...,236,3.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974,1,3,4,NaN,1705,NaN,1810,WN,1219,NaN,...,325,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
980,1,3,4,1243.0,1220,1345.0,1325,WN,2614,N602SW,...,325,2.0,10.0,NaN,20.0,0.0,0.0,0.0,0.0,0.0
972,1,3,4,2051.0,2015,2151.0,2120,WN,1150,N235WN,...,325,2.0,10.0,NaN,14.0,0.0,0.0,0.0,17.0,1.0
992,1,3,4,1620.0,1520,2144.0,2100,WN,78,N268WN,...,1642,3.0,12.0,NaN,14.0,0.0,0.0,0.0,30.0,1.0
967,1,3,4,1953.0,1935,2218.0,2200,WN,2612,N479WN,...,511,3.0,18.0,NaN,18.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
import pandas as pd

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Proyectos\Salle\SeminarioDataScience\archivos_base_python_data_science_big_data_esencial\base_datos_2008.csv\base_datos_2008.csv")

In [2]:
len(df)

7009728

In [3]:
df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [4]:
df.groupby(by="DayOfWeek")   ["ArrDelay"].max()

DayOfWeek
1    1583.0
2    1951.0
3    1510.0
4    2453.0
5    1707.0
6    1525.0
7    2461.0
Name: ArrDelay, dtype: float64

In [10]:
agrupa = df.groupby(by="DayOfWeek")["ArrDelay"].min()
agrupa

agrupa["max"] = df.groupby(by="DayOfWeek")["ArrDelay"].max()
agrupa.head()

DayOfWeek
1   -519.0
2    -89.0
3    -87.0
4   -129.0
5    -86.0
Name: ArrDelay, dtype: object

In [12]:
agrupa

DayOfWeek
1                                                 -519.0
2                                                  -89.0
3                                                  -87.0
4                                                 -129.0
5                                                  -86.0
6                                                  -91.0
7                                                  -92.0
max    DayOfWeek
1    1583.0
2    1951.0
3    1510.0
...
Name: ArrDelay, dtype: object

In [11]:
type(agrupa)

pandas.core.series.Series

In [13]:
agrupa = df.groupby(by="DayOfWeek")["ArrDelay"].min()
agrupa.head()
type(agrupa)

pandas.core.series.Series

In [14]:
agrupa.head()

DayOfWeek
1   -519.0
2    -89.0
3    -87.0
4   -129.0
5    -86.0
Name: ArrDelay, dtype: float64

In [15]:
df2 = pd.DataFrame(agrupa)
df2.rename(columns={"ArrDelay":"RetrasoMinimo"}, inplace=True)

In [16]:
df2

           RetrasoMinimo
DayOfWeek
1                 -519.0
2                  -89.0
3                  -87.0
4                 -129.0
5                  -86.0
6                  -91.0
7                  -92.0

In [17]:
agrupa = df.groupby(by="DayOfWeek")["ArrDelay"].max()
df2["RetrasoMax"] = agrupa
df2

           RetrasoMinimo  RetrasoMax
DayOfWeek
1                 -519.0      1583.0
2                  -89.0      1951.0
3                  -87.0      1510.0
4                 -129.0      2453.0
5                  -86.0      1707.0
6                  -91.0      1525.0
7                  -92.0      2461.0

In [18]:
agrupa = df.groupby(by="DayOfWeek")["ArrDelay"].mean()
df2["RetrasoPromedio"] = agrupa
df2

           RetrasoMinimo  RetrasoMax  RetrasoPromedio
DayOfWeek
1                 -519.0      1583.0         8.210850
2                  -89.0      1951.0         7.481208
3                  -87.0      1510.0         6.522017
4                 -129.0      2453.0         8.411599
5                  -86.0      1707.0        10.953440
6                  -91.0      1525.0         5.789666
7                  -92.0      2461.0         9.495886

In [19]:
df.groupby(by="DayOfWeek")["ArrDelay"].describe()

               count       mean        std    min   25%  50%   75%     max
DayOfWeek
1          1013410.0   8.210850  38.013811 -519.0 -10.0 -2.0  12.0  1583.0
2          1005992.0   7.481208  38.361073  -89.0 -11.0 -3.0  11.0  1951.0
3          1016995.0   6.522017  36.024679  -87.0 -10.0 -3.0  10.0  1510.0
4          1011970.0   8.411599  37.397411 -129.0 -10.0 -1.0  12.0  2453.0
5          1008872.0  10.953440  40.252320  -86.0  -9.0  0.0  15.0  1707.0
6           841663.0   5.789666  37.163120  -91.0 -11.0 -3.0   9.0  1525.0
7           956127.0   9.495886  41.759296  -92.0 -10.0 -2.0  12.0  2461.0

In [20]:
df.groupby(by="DayOfWeek")[["ArrDelay","DepDelay"]].max()

C:\Users\Jsilva\AppData\Local\Temp/ipykernel_31624/3499575819.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(by="DayOfWeek")["ArrDelay","DepDelay"].max()

           ArrDelay  DepDelay
DayOfWeek
1            1583.0    1552.0
2            1951.0    1952.0
3            1510.0    1518.0
4            2453.0    2467.0
5            1707.0    1710.0
6            1525.0    1521.0
7            2461.0    2457.0

In [21]:
df.groupby(by="DayOfWeek")["ArrDelay"].max() - df.groupby(by="DayOfWeek")["ArrDelay"].min()

DayOfWeek
1    2102.0
2    2040.0
3    1597.0
4    2582.0
5    1793.0
6    1616.0
7    2553.0
Name: ArrDelay, dtype: float64

In [22]:
pd.DataFrame((df.groupby(by="DayOfWeek")["ArrDelay"].max() - df.groupby(by="DayOfWeek")["ArrDelay"].min())).rename(columns={"ArrDelay":"RangoRetrasos"}).sort_values(["RangoRetrasos"],ascending=[False])

           RangoRetrasos
DayOfWeek
4                 2582.0
7                 2553.0
1                 2102.0
2                 2040.0
5                 1793.0
6                 1616.0
3                 1597.0

In [23]:
df[df.Origin.isin(["LAX","HOU"])].groupby(by=["DayOfWeek","Origin"])["ArrDelay"].mean()

DayOfWeek  Origin
1          HOU        6.356856
           LAX        5.143895
2          HOU        9.348112
           LAX        2.912576
3          HOU        9.073109
           LAX        3.583050
4          HOU       12.994016
           LAX        5.620814
5          HOU       11.036545
           LAX        7.368246
6          HOU        4.283933
           LAX        3.710689
7          HOU        7.045287
           LAX        8.348621
Name: ArrDelay, dtype: float64

In [24]:
agrupacion = df[df.Origin.isin(["LAX","HOU"])].groupby(by=["DayOfWeek","Origin"])["ArrDelay"]

In [25]:
agrupacion.mean()

DayOfWeek  Origin
1          HOU        6.356856
           LAX        5.143895
2          HOU        9.348112
           LAX        2.912576
3          HOU        9.073109
           LAX        3.583050
4          HOU       12.994016
           LAX        5.620814
5          HOU       11.036545
           LAX        7.368246
6          HOU        4.283933
           LAX        3.710689
7          HOU        7.045287
           LAX        8.348621
Name: ArrDelay, dtype: float64

In [26]:
len(df)

7009728

In [8]:
import pandas as pd
df = pd.read_csv(r"C:\Proyectos\Salle\SeminarioDataScience\archivos_base_python_data_science_big_data_esencial\base_datos_2008.csv\base_datos_2008.csv")

In [9]:
len(df)

7009728

In [13]:
df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [14]:
## 
df2 = df.drop_duplicates()

In [15]:
len(df2)

7009724

In [23]:
df.drop_duplicates(subset="FlightNum")

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6119438,2008,11,27,4,1551.0,1553,1759.0,1807,OO,6272,...,4.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
6609041,2008,12,14,7,1625.0,1600,1725.0,1707,OH,6857,...,25.0,25.0,0,NaN,0,18.0,0.0,0.0,0.0,0.0
6609916,2008,12,16,2,1131.0,1131,1226.0,1219,OH,6858,...,6.0,24.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
6611861,2008,12,20,6,640.0,630,810.0,756,OH,6947,...,3.0,20.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
6616659,2008,12,31,3,1710.0,1640,1905.0,1753,OH,6870,...,5.0,50.0,0,NaN,0,30.0,0.0,42.0,0.0,0.0

In [22]:
dforiginunico

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
19,2008,1,3,4,1416.0,1325,1512.0,1435,WN,54,...,2.0,5.0,0,NaN,0,12.0,0.0,0.0,0.0,25.0
47,2008,1,3,4,831.0,830,1148.0,1140,WN,534,...,5.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
56,2008,1,3,4,948.0,925,959.0,940,WN,3430,...,3.0,9.0,0,NaN,0,0.0,0.0,0.0,0.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3790987,2008,7,7,1,NaN,1750,NaN,1920,OO,5751,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
3791022,2008,7,7,1,1727.0,1736,1916.0,1920,OO,5779,...,5.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4694489,2008,8,20,3,600.0,600,738.0,725,9E,2919,...,13.0,26.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5524646,2008,10,1,3,1130.0,1140,1211.0,1235,OH,6449,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
6348854,2008,11,9,7,809.0,800,922.0,923,9E,2691,...,7.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [24]:
dfok = df.dropna(subset=["ArrDelay"])

In [25]:
len(dfok)

6855029

In [26]:
7009724 - 6855029

154695

In [28]:
df[df.ArrDelay.isnull()]

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
178,2008,1,3,4,NaN,700,NaN,830,WN,126,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
373,2008,1,3,4,NaN,1100,NaN,1215,WN,1146,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
399,2008,1,3,4,NaN,905,NaN,1025,WN,469,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
401,2008,1,3,4,NaN,1620,NaN,1740,WN,618,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
415,2008,1,3,4,NaN,1930,NaN,2035,WN,2528,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7009455,2008,12,13,6,NaN,600,NaN,815,DL,1211,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
7009464,2008,12,13,6,NaN,1930,NaN,2129,DL,1218,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
7009564,2008,12,13,6,NaN,700,NaN,1035,DL,1421,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
7009565,2008,12,13,6,NaN,1115,NaN,1432,DL,1422,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
7009648,2008,12,13,6,NaN,1020,NaN,1126,DL,1532,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN

In [29]:
df.loc[df.ArrDelay.isnull(),"ArrDelay"] = -1

In [34]:
df = pd.DataFrame([['No1',2], [4,5], [7,8],['7,000','8,000']], 
                  index=['cobra', 'viper', 'sidewinder','comasnumero'], 
                  columns=['max_speed', 'shield'])

In [37]:
type(df)
df.columns
df.dtypes

max_speed    object
shield       object
dtype: object

In [38]:
df.head()

            max_speed shield
cobra             No1      2
viper               4      5
sidewinder          7      8
comasnumero     7,000  8,000

In [39]:
df["max_speed"] = df["max_speed"].astype(str)
df["shield"] = df["shield"].astype(str)
df["max_speedb"] = df["max_speed"].str.isnumeric()
df["shieldb"] = df["shield"].str.isnumeric()
df

            max_speed shield  max_speedb  shieldb
cobra             No1      2       False     True
viper               4      5        True     True
sidewinder          7      8        True     True
comasnumero     7,000  8,000       False    False

In [40]:
df[df["max_speedb"]== False]

            max_speed shield  max_speedb  shieldb
cobra             No1      2       False     True
comasnumero     7,000  8,000       False    False

In [41]:
df.loc[df["max_speedb"]== False,"max_speed"] = df["max_speed"].str.replace(",", "")

In [42]:
df

            max_speed shield  max_speedb  shieldb
cobra             No1      2       False     True
viper               4      5        True     True
sidewinder          7      8        True     True
comasnumero      7000  8,000       False    False

In [46]:
df["max_speedb"] = df["max_speed"].str.isnumeric()
df

            max_speed shield max_speedb  shieldb
cobra               0      2        NaN     True
viper               4      5       True     True
sidewinder          7      8       True     True
comasnumero      7000  8,000       True    False

In [44]:
df.loc[df["max_speedb"]== False,"max_speed"] = 0
df

            max_speed shield  max_speedb  shieldb
cobra               0      2       False     True
viper               4      5        True     True
sidewinder          7      8        True     True
comasnumero      7000  8,000        True    False

In [45]:
df.dtypes

max_speed     object
shield        object
max_speedb      bool
shieldb         bool
dtype: object

In [ ]:
df["max_speedb"] = df["max_speed"].str.isnumeric()
df

In [47]:
df["max_speed"] = df["max_speed"].astype(int)
df

             max_speed shield max_speedb  shieldb
cobra                0      2        NaN     True
viper                4      5       True     True
sidewinder           7      8       True     True
comasnumero       7000  8,000       True    False

In [48]:
df.dtypes

max_speed      int32
shield        object
max_speedb    object
shieldb         bool
dtype: object

In [ ]:
df.loc[df["shieldb"]== False,"shield"] = df["shield"].str.replace(",", "")